### ISSUE TITLE
Error associated with 'name'

### ISSUE THREAD

**Issue by pedrosimao** [AhnSeongHyun/postman2md#5]
I am running on MacOSx environment, python 2.7 and Collection v.2. And I get the following error:
```
'name'
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    postman2md.convert(postman_file="TimeVallee.postman_collection_v2.json", multi_file=False)
  File "/Users/pedro1/Downloads/postman2md/postman2md/__init__.py", line 100, in convert
    raise e
KeyError: 'name'
```

**Comment by pedrosimao** [comment]
On your example it works correctly though. Do you want to check my Json file, to see if there is something odd about it?
https://drive.google.com/open?id=1CvCbWW1FnmlTBJ_P2kKcKPivs7c8W180
